// The 27 entries and lesson-specific senses come from the supplied conversation.
// Sentences, memory cues, and exercises are original teaching material.
const item = (
  id,
  german,
  english,
  kind,
  example,
  translation,
  tip,
  usages,
  forms = [],
) => ({ id, german, english, kind, example, translation, tip, usages, forms });
export const WORDS = [
  item(
    "brief",
    "der Brief",
    "letter",
    "noun",
    "Ich schreibe einen Brief.",
    "I am writing a letter.",
    "Learn der Brief → die Briefe. In Ich schreibe einen Brief, einen means a: Brief receives the action, so masculine ein changes to einen. Brief keeps its capital B. Its long ee sound is written ie.",
    [
      ["Ich schreibe einen ___.", "I am writing a letter.", "Brief"],
      ["Der ___ ist für dich.", "The letter is for you.", "Brief"],
    ],
    [
      [
        "Write the plural of der Brief, including die.",
        "die Briefe",
        "One letter: der Brief. Several letters: die Briefe. Add -e. Use die for the plural in this naming exercise; articles can change in other sentence roles.",
      ],
      [
        "Complete: ___ Brief (the letter).",
        "der",
        "Brief is masculine: der Brief.",
      ],
    ],
  ),
  item(
    "fuehlen",
    "sich fühlen",
    "to feel",
    "reflexive verb",
    "Ich fühle mich gut.",
    "I feel good.",
    "English says I feel good. German says Ich fühle mich gut: it needs mich here, although English does not say myself. Match ich → mich, du → dich, wir → uns. For ü, try saying ee with rounded lips, then listen and copy the German sound. Keep the h after ü.",
    [
      ["Ich ___ mich gut.", "I feel good.", "fühle"],
      ["Wir ___ uns müde.", "We feel tired.", "fühlen"],
    ],
    [
      [
        "Complete: Ich fühle ___ gut.",
        "mich",
        "With ich, use mich: Ich fühle mich gut.",
      ],
      [
        "Complete: Du fühlst ___ müde.",
        "dich",
        "With du, use dich: Du fühlst dich müde.",
      ],
    ],
  ),
  item(
    "aergern",
    "sich ärgern",
    "to get annoyed",
    "reflexive verb",
    "Ich ärgere mich über den Lärm.",
    "I am annoyed about the noise.",
    "Learn sich ärgern über …: to get annoyed about something. Ich ärgere mich means I get annoyed; wir ärgern uns means we get annoyed. English leaves out myself/ourselves here, but German needs mich/uns. Start ärgern with ä.",
    [
      [
        "Ich ___ mich über den Lärm.",
        "I am annoyed about the noise.",
        "ärgere",
      ],
      [
        "Wir ___ uns über den Regen.",
        "We are annoyed about the rain.",
        "ärgern",
      ],
    ],
    [
      [
        "Complete: Ich ärgere ___ über den Lärm.",
        "mich",
        "Ich pairs with mich. The extra e in ärgere belongs to the ich form.",
      ],
      [
        "Complete: Wir ärgern ___ über den Regen.",
        "uns",
        "Wir pairs with uns: Wir ärgern uns.",
      ],
    ],
  ),
  item(
    "traurig",
    "traurig",
    "sad",
    "adjective",
    "Ich bin traurig.",
    "I am sad.",
    "Ich bin traurig means I am sad. Spell trau + rig. The au sounds like ow in cow. Listen to the German ending: even when it sounds like ich, write ig. Traurig is sad; müde is tired.",
    [
      ["Ich bin ___.", "I am sad.", "traurig"],
      ["Mein Freund ist ___.", "My friend is sad.", "traurig"],
    ],
  ),
  item(
    "job",
    "der Job",
    "job",
    "noun",
    "Mein Vater hat einen Job.",
    "My father has a job.",
    "Learn der Job → die Jobs: the plural adds s. German nouns need a capital. In Mein Vater hat einen Job, einen means a; masculine ein changes to einen for the thing someone has.",
    [
      ["Mein Vater hat einen ___.", "My father has a job.", "Job"],
      ["Der ___ ist interessant.", "The job is interesting.", "Job"],
    ],
    [
      [
        "Write the plural of der Job, including die.",
        "die Jobs",
        "Add -s: Job → Jobs.",
      ],
      ["Complete: ___ Job (the job).", "der", "Job is masculine: der Job."],
    ],
  ),
  item(
    "mitkommen",
    "mitkommen",
    "to come along",
    "separable verb",
    "Ich komme mit.",
    "I am coming along.",
    "mitkommen means come along. Learn Ich komme mit — I am coming along. Change the verb for the person: du kommst, wir kommen. In these simple statements, keep mit at the end. The dictionary form mitkommen is one word, with double m.",
    [
      ["Ich komme heute ___.", "I am coming along today.", "mit"],
      ["Du ___ heute mit.", "You are coming along today.", "kommst"],
    ],
    [
      [
        "Fill both blanks, in order: Ich ___ heute ___. (come along)",
        "komme mit",
        "Conjugate kommen → komme. Put mit at the end: Ich komme heute mit.",
      ],
      [
        "Fill both blanks, in order: Wir ___ heute ___. (come along)",
        "kommen mit",
        "With wir, use kommen. The prefix mit goes at the end.",
      ],
    ],
  ),
  item(
    "umziehen",
    "umziehen",
    "to move (home)",
    "separable verb",
    "Wir ziehen nach Berlin um.",
    "We are moving to Berlin.",
    "Here umziehen means move home, not walk across a room. Ich ziehe um — I am moving. Wir ziehen um — We are moving. In these statements um goes last. In ziehen, ie makes a long ee sound and is followed by a silent h.",
    [
      ["Wir ziehen nach Berlin ___.", "We are moving to Berlin.", "um"],
      ["Ich ___ morgen um.", "I am moving tomorrow.", "ziehe"],
    ],
    [
      [
        "Fill both blanks, in order: Wir ___ morgen ___. (move home)",
        "ziehen um",
        "Wir ziehen morgen um. The prefix um goes at the end.",
      ],
      [
        "Fill both blanks, in order: Ich ___ heute ___. (move home)",
        "ziehe um",
        "Ich needs ziehe. Keep um at the end.",
      ],
    ],
  ),
  item(
    "weit-weg",
    "weit weg",
    "far away",
    "expression",
    "Meine Freundin wohnt weit weg.",
    "My friend lives far away.",
    "weit means far; weg means away. Keep two words: weit weg. In weit, ei sounds like English eye. Hear the final sound in weg, but remember the written ending is g.",
    [
      ["Meine Freundin wohnt ___.", "My friend lives far away.", "weit weg"],
      ["Berlin ist ___.", "Berlin is far away.", "weit weg"],
    ],
  ),
  item(
    "fast",
    "fast",
    "almost",
    "adverb",
    "Ich bin fast fertig.",
    "I am almost finished.",
    "False friend! German fast means almost. English fast would usually be schnell.",
    [
      ["Ich bin ___ fertig.", "I am almost finished.", "fast"],
      ["Es ist ___ acht Uhr.", "It is almost eight o’clock.", "fast"],
    ],
  ),
  item(
    "treffen",
    "sich treffen",
    "to meet (each other)",
    "reflexive verb",
    "Wir treffen uns im Park.",
    "We are meeting in the park.",
    "Double f: treffen. For meeting each other, use uns with wir and euch with ihr.",
    [
      ["Wir ___ uns im Park.", "We are meeting in the park.", "treffen"],
      ["Ich ___ mich mit Ben.", "I am meeting Ben.", "treffe"],
    ],
    [
      [
        "Complete: Wir treffen ___ im Park.",
        "uns",
        "Wir treffen uns means we meet each other.",
      ],
      [
        "Complete: Ihr trefft ___ im Park.",
        "euch",
        "With ihr, use euch: Ihr trefft euch.",
      ],
    ],
  ),
  item(
    "beide",
    "beide",
    "both",
    "pronoun",
    "Wir sind beide müde.",
    "We are both tired.",
    "beide means both of two: Wir sind beide müde — We are both tired. In beide, ei sounds like English eye. Contrast einige: some or several, without specifying exactly two.",
    [
      ["Wir sind ___ müde.", "We are both tired.", "beide"],
      [
        "Die zwei Freunde kommen ___.",
        "The two friends are both coming.",
        "beide",
      ],
    ],
  ),
  item(
    "fahrradtrial",
    "der Fahrradtrial",
    "bike trial",
    "noun",
    "Der Fahrradtrial ist schwer.",
    "The bike trial is difficult.",
    "Bike trials involves balancing and riding over obstacles, not following a trail. Build Fahr + rad + trial; the r letters meet. Your class sheet uses der Fahrradtrial → die Fahrradtrials. The sporting word Trial is normally das Trial; ask your teacher about this article difference. These exercises follow the sheet.",
    [
      ["Der ___ ist schwer.", "The bike trial is difficult.", "Fahrradtrial"],
      [
        "Ich finde den ___ spannend.",
        "I find the bike trial exciting.",
        "Fahrradtrial",
      ],
    ],
    [
      [
        "Write the plural of der Fahrradtrial, including die.",
        "die Fahrradtrials",
        "In this lesson, use der Fahrradtrial and die Fahrradtrials.",
      ],
      [
        "Complete: ___ Fahrradtrial (the bike trial).",
        "der",
        "Learn the article supplied in your lesson: der Fahrradtrial.",
      ],
    ],
  ),
  item(
    "hochfahren",
    "hochfahren",
    "to go up (by vehicle)",
    "separable verb",
    "Ich fahre den Berg hoch.",
    "I am riding up the mountain.",
    "hochfahren means ride or drive up. Compare Ich fahre hoch — I ride up; Er fährt hoch — He rides up. With er, a changes to ä; wir keeps fahren. In these simple statements hoch goes at the end. Keep the silent h in fahren.",
    [
      ["Ich fahre den Berg ___.", "I am riding up the mountain.", "hoch"],
      ["Wir ___ den Berg hoch.", "We are riding up the mountain.", "fahren"],
    ],
    [
      [
        "Fill both blanks, in order: Ich ___ den Berg ___. (ride up)",
        "fahre hoch",
        "Ich fahre den Berg hoch. The prefix hoch goes at the end.",
      ],
      [
        "Fill both blanks, in order: Er ___ den Berg ___. (rides up)",
        "fährt hoch",
        "Compare ich fahre and er fährt: with er, a changes to ä and the ending is t. Er fährt den Berg hoch — He rides up the mountain. Put hoch at the end.",
      ],
    ],
  ),
  item(
    "hoffentlich",
    "hoffentlich",
    "hopefully",
    "adverb",
    "Hoffentlich kommt sie mit.",
    "Hopefully she will come along.",
    "Split it: hoffen + tlich. There are two f letters and a t before lich.",
    [
      ["Sie kommt ___ mit.", "She will hopefully come along.", "hoffentlich"],
      [
        "Wir treffen uns ___ morgen.",
        "We will hopefully meet tomorrow.",
        "hoffentlich",
      ],
    ],
  ),
  item(
    "treppe",
    "die Treppe",
    "stairs / staircase",
    "noun",
    "Die Treppe ist hoch.",
    "The staircase is high.",
    "die Treppe means one staircase. English often calls this the stairs, but German Treppe is singular. Multiple staircases: die Treppen. Keep capital T and double p. Ich gehe die Treppe hoch means I am going up the stairs.",
    [
      ["Die ___ ist hoch.", "The staircase is high.", "Treppe"],
      ["Ich gehe die ___ hoch.", "I am going up the stairs.", "Treppe"],
    ],
    [
      [
        "Write the plural of die Treppe, including die.",
        "die Treppen",
        "One staircase: die Treppe. Several staircases: die Treppen. Add n. English the stairs can describe just one German Treppe.",
      ],
      [
        "Complete: ___ Treppe (the staircase).",
        "die",
        "Treppe is feminine: die Treppe.",
      ],
    ],
  ),
  item(
    "stark",
    "stark",
    "strong",
    "adjective",
    "Mein Bruder ist stark.",
    "My brother is strong.",
    "Picture someone lifting something heavy: stark = strong. Finish with rk.",
    [
      ["Mein Bruder ist ___.", "My brother is strong.", "stark"],
      ["Wir sind ___.", "We are strong.", "stark"],
    ],
  ),
  item(
    "streiten",
    "streiten",
    "to argue",
    "verb",
    "Wir streiten oft.",
    "We argue often.",
    "streiten means argue: wir streiten — we argue. Use ich streite, but er streitet: the extra e before t helps you say the ending. The ei sounds like English eye. Arguing is an action; sich ärgern means feeling annoyed.",
    [
      ["Wir ___ oft.", "We argue often.", "streiten"],
      ["Die Freunde ___ nicht.", "The friends do not argue.", "streiten"],
    ],
    [
      [
        "Complete: Ich ___ nicht. (argue)",
        "streite",
        "For ich, drop -n from streiten: ich streite.",
      ],
      [
        "Complete: Er ___ oft. (argues)",
        "streitet",
        "The er form is streitet. The extra e makes the ending pronounceable.",
      ],
    ],
  ),
  item(
    "muede",
    "müde",
    "tired",
    "adjective",
    "Ich bin müde.",
    "I am tired.",
    "Ich bin müde — I am tired. For ü, try ee with rounded lips, then listen and copy the German sound. Keep the dots: u is a different vowel. Spell mü + de. Needing sleep is müde, not traurig (sad).",
    [
      ["Ich bin ___.", "I am tired.", "müde"],
      ["Nach der Schule sind wir ___.", "After school we are tired.", "müde"],
    ],
  ),
  item(
    "schlecht",
    "schlecht",
    "bad",
    "adjective",
    "Das Wetter ist schlecht.",
    "The weather is bad.",
    "schlecht means bad. Build sch + le + ch + t. The first sch sounds like English sh; the later ch is a different German sound, not English ch in chair. Listen and copy. Keep both h letters.",
    [
      ["Das Wetter ist ___.", "The weather is bad.", "schlecht"],
      ["Der Film ist ___.", "The movie is bad.", "schlecht"],
    ],
  ),
  item(
    "verliebt",
    "verliebt",
    "in love",
    "adjective",
    "Ich bin verliebt.",
    "I am in love.",
    "Liebe means love. Build ver + lieb + t: verliebt means in love. Ich bin verliebt — I am in love. The ie sounds like ee; keep written bt even when the b sounds like p.",
    [
      ["Ich bin ___.", "I am in love.", "verliebt"],
      ["Sie ist ___.", "She is in love.", "verliebt"],
    ],
  ),
  item(
    "bestimmt",
    "bestimmt",
    "definitely",
    "adverb",
    "Er kommt bestimmt mit.",
    "He is definitely coming along.",
    "In this lesson, bestimmt means definitely. Double m: be-stimmt.",
    [
      ["Er kommt ___ mit.", "He is definitely coming along.", "bestimmt"],
      ["Das ist ___ richtig.", "That is definitely right.", "bestimmt"],
    ],
  ),
  item(
    "gluecklich",
    "glücklich",
    "happy",
    "adjective",
    "Ich bin glücklich.",
    "I am happy.",
    "Ich bin glücklich — I am happy. Build Glück + lich, then use a lowercase g for the adjective. Keep ü, ck, and the different ending ch. Compare glücklich (happy) and traurig (sad). Listen to ü and ch before repeating.",
    [
      ["Ich bin ___.", "I am happy.", "glücklich"],
      ["Meine Freunde sind ___.", "My friends are happy.", "glücklich"],
    ],
  ),
  item(
    "sensibel",
    "sensibel",
    "sensitive",
    "adjective",
    "Mein Freund ist sensibel.",
    "My friend is sensitive.",
    "Another false friend: sensibel means sensitive, not sensible. It ends in -bel.",
    [
      ["Mein Freund ist ___.", "My friend is sensitive.", "sensibel"],
      ["Sie ist sehr ___.", "She is very sensitive.", "sensibel"],
    ],
  ),
  item(
    "fleissig",
    "fleißig",
    "hard-working",
    "adjective",
    "Sie ist fleißig.",
    "She is hard-working.",
    "fleißig means hard-working: Sie ist fleißig — She works hard. Build fleiß + ig. The ei sounds like English eye; ß sounds like s, not b. Keep the written ending ig. Use the ß key below the answer box.",
    [
      ["Sie ist ___.", "She is hard-working.", "fleißig"],
      ["Wir sind ___.", "We are hard-working.", "fleißig"],
    ],
  ),
  item(
    "zuhoeren",
    "zuhören",
    "to listen",
    "separable verb",
    "Ich höre dir zu.",
    "I am listening to you.",
    "Learn Ich höre dir zu — I am listening to you. German uses dir, not dich, with zuhören: learn höre dir zu as a phrase. Wir hören dir zu — We are listening to you. In these simple statements zu goes last. Listen to ö; it is not the same sound as o.",
    [
      ["Ich höre dir ___.", "I am listening to you.", "zu"],
      ["Wir ___ der Lehrerin zu.", "We are listening to the teacher.", "hören"],
    ],
    [
      [
        "Fill both blanks, in order: Ich ___ dir ___. (listen)",
        "höre zu",
        "Ich höre dir zu. Keep ö in höre and put zu at the end.",
      ],
      [
        "Fill both blanks, in order: Wir ___ dir ___. (listen)",
        "hören zu",
        "Wir hören dir zu. The prefix zu goes at the end.",
      ],
    ],
  ),
  item(
    "einige",
    "einige",
    "some / several",
    "determiner",
    "Einige Freunde kommen mit.",
    "Some friends are coming along.",
    "einige means some or several. It does not mean exactly two; that is beide.",
    [
      ["Wir haben ___ Bücher.", "We have several books.", "einige"],
      ["Ich schreibe ___ Briefe.", "I am writing some letters.", "einige"],
    ],
  ),
  item(
    "interessieren",
    "sich interessieren",
    "to be interested",
    "reflexive verb",
    "Ich interessiere mich für Musik.",
    "I am interested in music.",
    "There are two r letters, neither doubled: one in inter and another in ieren. Keep double s: inter + ess + ieren. Learn Ich interessiere mich für Musik — I am interested in music. German needs mich and für here; do not translate English in word for word.",
    [
      ["Ich ___ mich für Musik.", "I am interested in music.", "interessiere"],
      [
        "Wir ___ uns für Sport.",
        "We are interested in sports.",
        "interessieren",
      ],
    ],
    [
      [
        "Complete: Ich interessiere ___ für Musik.",
        "mich",
        "Ich pairs with mich. Für means in in this expression.",
      ],
      [
        "Complete: Wir interessieren ___ für Sport.",
        "uns",
        "Wir pairs with uns: Wir interessieren uns für Sport.",
      ],
    ],
  ),
];

export const BY_ID = Object.fromEntries(WORDS.map((word) => [word.id, word]));
export const SKILL_LABELS = {
  meaning: "Meaning",
  spelling: "Spelling & recall",
  usage: "Sentence use",
  form: "Word forms",
};
export const requiredSkills = (word) => [
  "meaning",
  "spelling",
  "usage",
  ...(word.forms.length ? ["form"] : []),
];
