// Wave 2: teacher-supplied autumn vocabulary; original beginner teaching material.
// Freeze these targets before study. Never change an active wave's word identities.
const noun = (id, singular, plural, english, pluralEnglish, example, translation, usages, chunks, cue, spelling, rule) => {
  const article = singular.split(' ')[0];
  const german = id === 'gummistiefel' ? plural : singular;
  return {
    id, german, english, kind: 'noun', studyVersion: 2, example, translation,
    // Only the assigned form is assessed. Conversion remains optional reference.
    assessedFormVariants: id === 'gummistiefel' ? [] : [1],
    tip: `${singular} means ${id === 'gummistiefel' ? 'one rain boot' : english}. ${plural} means ${pluralEnglish}. ${rule} ${spelling} Learn the whole noun with its article. All German nouns start with a capital letter.`,
    usages,
    forms: [
      [`Write the plural of ${singular}, including die.`, plural, `Singular: ${singular}. Plural: ${plural}. ${rule}`],
      [`Complete the singular: ___ ${singular.split(' ').slice(1).join(' ')}.`, article, `For one, say ${singular}; for more than one, say ${plural}.`],
    ],
    nounForms: { singular, plural, singularEnglish: id === 'gummistiefel' ? 'one rain boot' : english, pluralEnglish, rule },
    memory: {scene: cue, watch: spelling, chunks, recall: `Picture the scene, cover the German, and write ${german}. Check every letter and the article.`},
  };
};

// Keep shipped recordings usable for saved historical content and optional reference.
const assignedSpelling = {
  oktoberfest: 'Write Oktober with k, not the English c. Join Oktober and fest into one word; capital O.',
  erntedankfest: 'Build Ernte + dank + fest without spaces. Keep the e in Ernte and the k in dank.',
  wanderung: 'Write Wander + ung: only one r in Wander. The noun ending -ung is a useful clue for die.',
  baum: 'Write B-au-m. Baum has au, with no umlaut. Learn der Baum.',
  blatt: 'Write Bl-a-tt. Blatt ends in double t. Learn das Blatt.',
  bauernhaus: 'Keep the n in Bauern. Build Bauern + haus without spaces, with capital B. Learn das Bauernhaus.',
  kuerbis: 'Kürbis has ü, one s, and no final e. The two dots belong over ü. Learn der Kürbis.',
  igel: 'Start with capital I, then gel. The long first vowel is written with just I: do not add an e.',
  laterne: 'Say and write La-ter-ne. Keep the e between t and r, and the final e.',
  spaziergang: 'Write Spa-zier-gang. The long ee sound in zier is written ie. Learn der Spaziergang.',
  ernte: 'Write Ern-te: keep r, n, and t in that order. Start with capital E and end with e.',
  drachen: 'For a kite, write Dra-chen with ch and a final n. Learn der Drachen, not der Drache.',
  gummistiefel: 'Gummi has double m. Stiefel has ie for its long ee sound. Join them: Gummistiefel. Learn the assigned die Gummistiefel: rain boots.',
};
const assignedScenes = {
  baum: 'Picture one blocky tree. Its label is der Baum. Connect the au letters with the tall trunk you can see.',
  igel: 'Picture a small hedgehog curled up beside a tree. Its label is der Igel. Check the capital I at the start.',
  gummistiefel: 'Picture a pair of rubber boots splashing in a puddle. Gummi means rubber; Stiefel means boot. Learn die Gummistiefel for the pair.',
};
function applyAssignedScope(wave) {
  return {...wave, words:wave.words.map(word => {
    if (word.kind !== 'noun') return word;
    const memory = {...word.memory, watch:assignedSpelling[word.id], scene:assignedScenes[word.id] || word.memory.scene};
    return {...word, memory,
      tip:`${word.german} means ${word.english}. ${memory.watch} Learn the whole assigned noun with its article. All German nouns start with a capital letter.`,
      forms:word.forms.map((form,i) => i !== 1 ? form : [form[0], form[1], `Learn the assigned noun ${word.german}, including its article. All German nouns start with a capital letter.`]),
    };
  })};
}
const adjective = (id, german, english, example, translation, usages, chunks, cue, spelling) => ({
  id, german, english, kind: 'adjective', studyVersion: 2, example, translation, usages, forms: [],
  tip: `${spelling} In these sentences the describing word comes after ist or sind; use ${german} unchanged. The other sentence words are supplied: you only fill in the describing word.`,
  memory: { scene: cue, watch: spelling, chunks, recall: `Picture the scene, hide the word, and write ${german} from memory. Check it letter by letter.` },
});

export const WAVE_TWO_REFERENCE = {
  id: 'wave-2-autumn-2026',
  title: 'Wave 2 · Autumn adventure',
  dueAt: '2026-10-05T09:00:00-04:00',
  words: [
    noun('oktoberfest', 'das Oktoberfest', 'die Oktoberfeste', 'Oktoberfest festival', 'Oktoberfest celebrations',
      'Das Oktoberfest ist ein Fest.', 'Oktoberfest is a festival.',
      [['Das ___ ist ein Fest.', 'Oktoberfest is a festival.', 'Oktoberfest'], ['Das ___ ist in München.', 'Oktoberfest is in Munich.', 'Oktoberfest']],
      ['Oktober', 'fest'], 'Picture an October festival with music and a giant pretzel. Oktober + Fest joins October and festival.',
      'Write Oktober with k, not the English c. Join Oktober and fest into one word; capital O.', 'For several separate celebrations, add -e. The famous Munich event is normally named in the singular.'),
    noun('erntedankfest', 'das Erntedankfest', 'die Erntedankfeste', 'harvest thanksgiving festival', 'harvest thanksgiving festivals',
      'Das Erntedankfest ist im Herbst.', 'The harvest thanksgiving festival is in autumn.',
      [['Das ___ ist im Herbst.', 'The harvest thanksgiving festival is in autumn.', 'Erntedankfest'], ['Wir feiern das ___.', 'We celebrate the harvest thanksgiving festival.', 'Erntedankfest']],
      ['Ernte', 'dank', 'fest'], 'Picture a harvest table: crops, a thank-you sign, and a festival. Ernte is harvest, Dank is thanks, and Fest is festival. It is not the American Thanksgiving holiday.',
      'Build Ernte + dank + fest without spaces. Keep the e in Ernte and the k in dank.', 'Add -e for several festivals.'),
    noun('wanderung', 'die Wanderung', 'die Wanderungen', 'hike', 'hikes',
      'Die Wanderung ist lang.', 'The hike is long.',
      [['Die ___ ist lang.', 'The hike is long.', 'Wanderung'], ['Wir machen eine ___.', 'We go on a hike.', 'Wanderung']],
      ['Wander', 'ung'], 'Picture a long hike along a forest trail. Connect Wanderung with English wander, but remember: this word names the hike.',
      'Write Wander + ung: only one r in Wander. The noun ending -ung is a useful clue for die.', 'Add -en: Wanderung → Wanderungen.'),
    noun('baum', 'der Baum', 'die Bäume', 'tree', 'trees',
      'Der Baum ist groß.', 'The tree is big.',
      [['Der ___ ist groß.', 'The tree is big.', 'Baum'], ['Der ___ hat Blätter.', 'The tree has leaves.', 'Baum']],
      ['B', 'au', 'm'], 'Picture one blocky tree; now add another tree and two dots over the a. One Baum becomes several Bäume.',
      'Singular Baum has au. Plural Bäume changes a to ä and adds e. Do not put the umlaut in the singular.', 'Change a → ä and add -e.'),
    noun('blatt', 'das Blatt', 'die Blätter', 'leaf', 'leaves',
      'Das Blatt ist gelb.', 'The leaf is yellow.',
      [['Das ___ ist gelb.', 'The leaf is yellow.', 'Blatt'], ['Das ___ fällt.', 'The leaf is falling.', 'Blatt']],
      ['Bl', 'a', 'tt'], 'Picture a leaf falling beside a tree. Give its stem two little branches to remind you of the two t letters. The word can also mean a sheet of paper; this wave uses leaf.',
      'Blatt ends in double t. Blätter keeps tt, changes a to ä, and adds er.', 'Change a → ä and add -er.'),
    noun('bauernhaus', 'das Bauernhaus', 'die Bauernhäuser', 'farmhouse', 'farmhouses',
      'Das Bauernhaus ist alt.', 'The farmhouse is old.',
      [['Das ___ ist alt.', 'The farmhouse is old.', 'Bauernhaus'], ['Das ___ ist auf dem Bauernhof.', 'The farmhouse is on the farm.', 'Bauernhaus']],
      ['Bauern', 'haus'], 'Picture the farmer’s house beside a field. Bauern + Haus builds one farmhouse word. Haus looks a little like English house.',
      'Keep the n in Bauern. Singular ends haus; plural ends häuser, with ä. Capital B, no space.', 'Only the house part changes: Haus → Häuser; keep Bauern unchanged.'),
    noun('kuerbis', 'der Kürbis', 'die Kürbisse', 'pumpkin', 'pumpkins',
      'Der Kürbis ist orange.', 'The pumpkin is orange.',
      [['Der ___ ist orange.', 'The pumpkin is orange.', 'Kürbis'], ['Der ___ ist groß.', 'The pumpkin is big.', 'Kürbis']],
      ['K', 'ür', 'bis'], 'Picture a pumpkin with two seeds above it: the two dots belong over ü. On the pumpkin’s label, check Kürbis before adding more pumpkins.',
      'Kürbis has ü, one s, and no final e. Kürbisse has double s and a final e.', 'Add -se to Kürbis: the resulting ending is -isse, with ss.'),
    noun('igel', 'der Igel', 'die Igel', 'hedgehog', 'hedgehogs',
      'Der Igel ist klein.', 'The hedgehog is small.',
      [['Der ___ ist klein.', 'The hedgehog is small.', 'Igel'], ['Der ___ hat Stacheln.', 'The hedgehog has spines.', 'Igel']],
      ['I', 'gel'], 'Picture one hedgehog, then a family of hedgehogs. Their name stays Igel; only der changes to die.',
      'Start with capital I, then gel. The long first vowel is written with just I: do not add an e.', 'The noun spelling does not change; change the article der → die.'),
    noun('laterne', 'die Laterne', 'die Laternen', 'lantern', 'lanterns',
      'Die Laterne leuchtet.', 'The lantern shines.',
      [['Die ___ leuchtet.', 'The lantern shines.', 'Laterne'], ['Die ___ ist bunt.', 'The lantern is colorful.', 'Laterne']],
      ['La', 'ter', 'ne'], 'Picture carrying a bright lantern on an autumn evening. English lantern and German Laterne share many letters; look carefully at the different ending.',
      'Say and write La-ter-ne. Keep the e between t and r, and the final e. Laternen adds n.', 'Add -n to Laterne.'),
    adjective('neblig', 'neblig', 'foggy', 'Es ist neblig.', 'It is foggy.',
      [['Es ist ___.', 'It is foggy.', 'neblig'], ['Der Morgen ist ___.', 'The morning is foggy.', 'neblig']],
      ['neb', 'lig'], 'Picture fog hiding the trees. Nebel means fog; neblig describes foggy weather. Compare Nebel with neblig: the middle e disappears.',
      'For this lesson, learn neblig: neb-lig. Nebelig is also a correct German spelling, but your assigned word is neblig. The last three letters are lig. Keep lowercase n.'),
    adjective('trueb', 'trüb', 'gloomy / dull', 'Der Tag ist trüb.', 'The day is gloomy.',
      [['Der Tag ist ___.', 'The day is gloomy.', 'trüb'], ['Das Wetter ist ___.', 'The weather is gloomy.', 'trüb']],
      ['tr', 'ü', 'b'], 'Picture a gray, gloomy sky with no bright sunshine. Two little clouds above the word remind you of the two dots on ü. Trüb describes dull weather here, not a sad person.',
      'Only four letters: t-r-ü-b. Keep ü; no final e. Listen to the rounded ü sound.'),
    adjective('malerisch', 'malerisch', 'picturesque / scenic', 'Das Dorf ist malerisch.', 'The village is picturesque.',
      [['Das Dorf ist ___.', 'The village is picturesque.', 'malerisch'], ['Die Landschaft ist ___.', 'The landscape is picturesque.', 'malerisch']],
      ['maler', 'isch'], 'Picture a village so beautiful that a painter wants to paint it. Maler means painter; malerisch means picturesque, like a lovely picture.',
      'Build maler + isch. The last four letters are isch; keep the three-letter sch together.'),
    adjective('regnerisch', 'regnerisch', 'rainy', 'Das Wetter ist regnerisch.', 'The weather is rainy.',
      [['Das Wetter ist ___.', 'The weather is rainy.', 'regnerisch'], ['Der Tag ist ___.', 'The day is rainy.', 'regnerisch']],
      ['reg', 'ner', 'isch'], 'Picture rain over your village. Regen means rain. Compare Regen and regnerisch: rain becomes the describing word rainy.',
      'Write reg-ner-isch. The beginning is regn, not regen. Finish with isch, including sch.'),
    adjective('kuehl', 'kühl', 'cool / chilly', 'Es ist kühl.', 'It is cool.',
      [['Es ist ___.', 'It is cool.', 'kühl'], ['Der Morgen ist ___.', 'The morning is chilly.', 'kühl']],
      ['k', 'üh', 'l'], 'Picture a cool autumn morning when you need a light jacket. Kühl is cool in temperature, not English cool meaning awesome.',
      'Write k-ü-h-l. Keep both the two dots over ü and the silent h after it.'),
    adjective('wasserdicht', 'wasserdicht', 'waterproof', 'Die Jacke ist wasserdicht.', 'The jacket is waterproof.',
      [['Die Jacke ist ___.', 'The jacket is waterproof.', 'wasserdicht'], ['Die Gummistiefel sind ___.', 'The rain boots are waterproof.', 'wasserdicht']],
      ['wasser', 'dicht'], 'Picture water rolling off your rain boots. Wasser is water; dicht can mean sealed. Together, wasserdicht means waterproof.',
      'Build wasser + dicht with no space. Wasser has double s; dicht ends cht. Lowercase w.'),
    adjective('dicht', 'dicht', 'dense / thick', 'Der Nebel ist dicht.', 'The fog is dense.',
      [['Der Nebel ist ___.', 'The fog is dense.', 'dicht'], ['Der Wald ist ___.', 'The forest is dense.', 'dicht']],
      ['di', 'cht'], 'Picture fog packed so closely that you cannot see the next tree. Dicht means dense here. It can also mean sealed, as in wasserdicht; the sentence tells you which meaning fits.',
      'Write d-i-c-h-t. Keep cht together; there is no second i or final e.'),
    noun('spaziergang', 'der Spaziergang', 'die Spaziergänge', 'walk / stroll', 'walks / strolls',
      'Der Spaziergang ist kurz.', 'The walk is short.',
      [['Der ___ ist kurz.', 'The walk is short.', 'Spaziergang'], ['Wir machen einen ___.', 'We go for a walk.', 'Spaziergang']],
      ['Spa', 'zier', 'gang'], 'Picture a relaxed stroll around your village, rather than a long hike. Spaziergang is the walk; Wanderung is the hike. Gang can mean a walk or going.',
      'Write Spa-zier-gang. The long ee sound in zier is written ie. In Wir machen einen Spaziergang, masculine ein changes to einen because the walk receives the action.', 'Keep Spazier unchanged; Gang → Gänge: a → ä, then add -e.'),
    noun('ernte', 'die Ernte', 'die Ernten', 'harvest', 'harvests',
      'Die Ernte ist gut.', 'The harvest is good.',
      [['Die ___ ist gut.', 'The harvest is good.', 'Ernte'], ['Die ___ ist im Herbst.', 'The harvest is in autumn.', 'Ernte']],
      ['Ern', 'te'], 'Picture gathering pumpkins and crops from the field. That harvest is die Ernte. The same Ernte starts Erntedankfest.',
      'Write Ern-te: keep r, n, and t in that order. Start with capital E and end with e.', 'Add -n to Ernte.'),
    noun('drachen', 'der Drachen', 'die Drachen', 'kite', 'kites',
      'Der Drachen fliegt.', 'The kite flies.',
      [['Der ___ fliegt.', 'The kite flies.', 'Drachen'], ['Der ___ ist bunt.', 'The kite is colorful.', 'Drachen']],
      ['Dra', 'chen'], 'Picture a colorful kite on a string in the wind. Keep its tail: the final n in Drachen. A mythical dragon is der Drache, without that final n in its singular name.',
      'For a kite, write Dra-chen with ch and a final n. Both one kite and several kites keep that n.', 'The noun spelling stays Drachen; change der → die for the plural.'),
    noun('gummistiefel', 'der Gummistiefel', 'die Gummistiefel', 'rain boots / rubber boots', 'rain boots / rubber boots',
      'Die Gummistiefel sind gelb.', 'The rain boots are yellow.',
      [['Die ___ sind gelb.', 'The rain boots are yellow.', 'Gummistiefel'], ['Die ___ sind wasserdicht.', 'The rain boots are waterproof.', 'Gummistiefel']],
      ['Gummi', 'stie', 'fel'], 'Picture a pair of rubber boots splashing in a puddle. Gummi means rubber; Stiefel means boot. Your lesson gives the plural: die Gummistiefel. One boot is der Gummistiefel.',
      'Gummi has double m. Stiefel has ie for its long ee sound. Join them: Gummistiefel. With several boots use sind, not singular ist.', 'The noun spelling stays the same. One: der Gummistiefel. More than one: die Gummistiefel.'),
  ].map(word => ({...word, meaningAnswers: [...new Set([
    ...word.english.split(/\s*\/\s*/),
    ...(word.id === 'oktoberfest' ? ['Oktoberfest', 'October festival'] : []),
    ...(word.id === 'erntedankfest' ? ['harvest festival', 'harvest thanksgiving'] : []),
  ])]})),
};
export const WAVE_TWO = applyAssignedScope(WAVE_TWO_REFERENCE);
